# Generated by Django 5.2.5 on 2025-08-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_session_id_transaction_session_and_more'),
        ('store', '0005_remove_orders_customer_remove_orders_total_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
