# Generated by Django 5.2.5 on 2025-08-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('items', models.JSONField()),
                ('customer', models.JSONField(default=dict)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed')], default=0)),
                ('payment_method', models.IntegerField(choices=[(0, 'Credit Card'), (1, 'PayPal')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
