# Generated by Django 5.2.5 on 2026-04-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_session_id_transaction_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Paypal'), (2, 'Stripe')]),
        ),
    ]
